# Generated by Django 5.0.3 on 2024-03-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
